# Generated by Django 2.2 on 2020-08-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=512)),
                ('content', models.TextField(max_length=256)),
                ('mail', models.CharField(max_length=100)),
                ('publish', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('song_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('song_no', models.IntegerField(db_column='歌曲序号')),
                ('song_name', models.CharField(db_column='歌名', max_length=50)),
                ('song_singer', models.CharField(db_column='歌手', max_length=50)),
                ('song_come', models.CharField(db_column='来源', max_length=100)),
                ('song_link', models.CharField(db_column='音乐链接', max_length=255)),
                ('song_img_link', models.CharField(db_column='图片链接', max_length=255)),
                ('search_type', models.CharField(db_column='搜索类别', max_length=20)),
                ('user_ip', models.CharField(db_column='用户IP', max_length=20)),
            ],
            options={
                'verbose_name': '歌曲信息',
                'verbose_name_plural': '歌曲信息',
            },
        ),
        migrations.CreateModel(
            name='music_key_statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_key', models.CharField(db_column='搜索关键词', max_length=100)),
                ('music_key_times', models.IntegerField(db_column='搜索次数')),
                ('user_ip', models.CharField(db_column='用户IP', max_length=20)),
            ],
        ),
    ]
